version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/files:/app/files
      - ./backend/db:/app/db
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1